### PR TITLE
Windows  build

### PR DESCRIPTION
**Pull request by hmaarrfk**
Builds off #3 

Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
THanks @paulparneix  who I built most of this off.

I really tried to combine the directories and follow best practices.

I tested this trying to build enblend, which requires lcms2 and seems to pass.

**Comment by kmilos** [comment]
I have a slightly different cmake take on this, I hope to submit a patch to your fork soon.

- No need to patch the def file, it can be dropped from sources list for now exclusive win64 builds
- Also build and install static lib

**Comment by hmaarrfk** [comment]
@isuruf, any interest in merging this to enable windows builds?

**Comment by isuruf** [comment]
Looks like they have visual studio solutions. https://github.com/mm2/Little-CMS/blob/ce6dea8aa9606c4824e8ed6223e6a8f3e8034f75/Projects/VC2017/lcms2.sln

I'm wary of building this with a new build system (cmake) that we have to maintain.

**Comment by hmaarrfk** [comment]
any guide on how to use that in the context of conda-forge?

**Comment by isuruf** [comment]
You need something like https://github.com/conda-forge/mpir-feedstock/blob/master/recipe/bld.bat#L23

**Comment by hmaarrfk** [comment]
The lib is called tiff.lib and not libtiff. I think that might be the issue

**Comment by hmaarrfk** [comment]
Not libtiff.lib

**Comment by isuruf** [comment]
rename it temporarily and delete afterwards?

**Comment by hmaarrfk** [comment]
Or maybe patch instead?

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
@isuruf this is ready for final review

**Comment by isuruf** [comment]
I don't like the patch and copying .lib is easier to maintain, but I won't hold this PR for that.

Will merge when tests pass.

**Comment by isuruf** [comment]
Thanks for the PR

**Comment by hmaarrfk** [comment]
Thank you very much for the help!

Opened an issue regarding the patch.

**Pull request merged**
