### PR TITLE
Include lcms2 static lib for win build

### PR DESCRIPTION
**Pull request by kmilos**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
I thought we wanted to encourage dynamic linking.

What challenge are you facing with dynamic ?

**Comment by kmilos** [comment]
No challenge per se, but there are projects building wheels using conda that prefer to link everything statically. See e.g. https://github.com/letmaik/rawpy/issues/103

And there are plenty of libraries already that ship both.

**Comment by hmaarrfk** [comment]
I guess this is above my involvement, and I was under the impression that we didn't want to do this.

I would like to see some guidance from @conda-forge/core before moving in the wrong direction.

**Comment by xhochy** [comment]
I would prefer that if we build static libs that they should be a separate output.

**Comment by kmilos** [comment]
There is already good precedence for shipping both shared and static libraries (after all, the *nix packages include both). Just an example in my env:

```
> dir *static.lib


    Directory: C:\Users\kmilos\.conda\envs\dev\Library\lib


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       31/12/2018     05:51        6552442 freeglut_static.lib
-a----       04/05/2020     18:34         543028 liblz4_static.lib
-a----       07/04/2020     11:27        6041174 liblzma_static.lib
-a----       19/03/2020     13:44        3765906 libpng16_static.lib
-a----       19/03/2020     13:44        3765906 libpng_static.lib
-a----       07/05/2019     21:14        1709528 libsodium_static.lib
-a----       11/04/2020     08:26        1167826 libzstd_static.lib
-a----       10/09/2019     01:24         831356 zlibstatic.lib
-a----       11/04/2020     08:26        1167826 zstd_static.lib
```

of course in addition to the shared implib and DLLs.

You would prefer to repackage those (and probably many more) differently?

**Comment by xhochy** [comment]
> You would prefer to repackage those (and probably many more) differently?

Yes.

**Comment by kmilos** [comment]
Dropping this as rawpy is switching to vcpkg for dependencies.

**Comment by hmaarrfk** [comment]
Oh no!!! kmilos your help was so appreciated with conda-forge!

**Comment by kmilos** [comment]
Don't worry, I'll still lurk around as conda-forge is my primary Python environment ;) This was just specific to rawpy needing static libs to build self-contained wheels in their CI...

**Pull request closed without merging**
